/*
 * Aura Common Header
 * Shared definitions for the Aura localized cloud service.
 * This file defines the communication channels, message types, and
 * data structures used by all components of the system.
 */
#ifndef AURA_COMMON_H
#define AURA_COMMON_H

#include <stdint.h>
#include <sys/types.h>
#include <stdbool.h>

// --- Public Channel Definitions ---
#define INGEST_CHANNEL   "aura-ingest-bus"
#define WORK_QUEUE_CHANNEL "aura-work-queue-bus"
#define QUERY_CHANNEL    "aura-query-bus"

// --- Message Type Definitions ---
#define MSG_SYS_SHUTDOWN 10

// Ingestion Messages
#define MSG_INGEST_FILE_REQUEST 101
#define MSG_INGEST_OP_REPLY     102

// Internal Work Queue Messages
#define MSG_JOB_ANALYZE_FILE    201
#define MSG_JOB_INDEX_FILE      202

// Query Messages
#define MSG_QUERY_SEARCH_REQUEST 301
#define MSG_QUERY_SEARCH_REPLY   302
#define MSG_QUERY_GET_METADATA_REQUEST 303
#define MSG_QUERY_GET_METADATA_REPLY   304

// --- Data Structures ---
#define MAX_FILENAME_SIZE 256
#define MAX_CONTENT_SIZE 16384 // 16 KB max file size for this demo
#define MAX_WORD_SIZE 64
#define MAX_SEARCH_RESULTS 100

// Sent from client to ingestd
typedef struct {
    pid_t client_pid;
    char filename[MAX_FILENAME_SIZE];
    uint32_t content_size;
    char content[MAX_CONTENT_SIZE];
} aura_ingest_request_t;

// A unique identifier for each file in the system
typedef uint64_t file_id_t;

// Generic reply for simple operations
typedef struct {
    bool success;
    file_id_t id; // Return the new file's ID on success
    char error_msg[128];
} aura_op_reply_t;

// The generic job packet placed on the work queue
typedef struct {
    uint16_t job_type; // e.g., MSG_JOB_ANALYZE_FILE
    file_id_t id;
    char filename[MAX_FILENAME_SIZE];
} aura_job_packet_t;

// The metadata generated by the analyst daemon
typedef struct {
    file_id_t id;
    uint32_t word_count;
    uint32_t line_count;
    uint32_t char_count;
    char filename[MAX_FILENAME_SIZE];
} aura_file_metadata_t;

// The search query from the client
typedef struct {
    pid_t client_pid;
    char query[MAX_WORD_SIZE];
} aura_search_request_t;

// A single search result entry
typedef struct {
    file_id_t id;
    uint32_t line_number;
} aura_search_result_t;

// The full reply from the query daemon
typedef struct {
    int result_count;
    aura_search_result_t results[MAX_SEARCH_RESULTS];
} aura_search_reply_t;

#endif // AURA_COMMON_H
